server:
  host: "localhost"
  port: 8081


database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "finance"

rabbitmq:
  uri: "amqp://guest:guest@localhost:5672/"
  queues:
   