definitions:
  presenter.UserBalanceRequest:
    properties:
      amount:
        type: number
      user_id:
        type: integer
    type: object
  presenter.UserBalanceResponse:
    properties:
      balance:
        type: number
      user_id:
        type: integer
    type: object
  presenter.UserRequest:
    properties:
      apikey:
        type: string
      balance:
        format: float64
        type: number
    type: object
  presenter.UserResponse:
    properties:
      apikey:
        type: string
      balance:
        type: number
      id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /{id}:
    get:
      consumes:
      - application/json
      description: Retrieve user details by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.UserResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user by ID
      tags:
      - users
  /create:
    post:
      consumes:
      - application/json
      description: Create a new user with an api key and initial balance
      parameters:
      - description: User request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/presenter.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.UserResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create user
      tags:
      - users
  /credit:
    put:
      consumes:
      - application/json
      description: Add amount to a user's balance
      parameters:
      - description: Balance request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/presenter.UserBalanceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.UserBalanceResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Credit user balance
      tags:
      - users
swagger: "2.0"
